# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71cd5e75e384acd17388f336f99085d3b86b766d750a7c3e5ce991bea96845786fe1b11e277e015af7982f12e7fb2ff0db9a3a2af63a03344f1ffd8b22336294

test:
  secret_key_base: f3d774093d14566c9a6d758ec2085fcdc3ce64dbd427f4147e4575ebf96245c8072332314340add96dc9d7c6e3eff492b85736969816dc4b5cf96e9d920f65fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
